### ISSUE TITLE
How does one exactly use the animation backporter?

### ISSUE THREAD

**Issue by Jordon87** [itsmeft24/cars-research#1]
wanted to try and use this tool to convert Race-O-Rama animations back into Mater-National ones, but i don't exactly know how to use it properly. Tried using the Python console, it keeps on saying:

No module named 'mathutils'

really hope you'll be able to help me get it to work for me.

**Comment by itsmeft24** [comment]
you need to install the mathutils package. sadly, the library does not work on python 3.10, so you have to use 3.8.

**Comment by Jordon87** [comment]
okie dokie.

one more thing, where do you get the mathutils package? i just don't know which one to pick.

**Comment by itsmeft24** [comment]
just use pip? it should be just as easy as doing a "pip install mathutils".

**Comment by Jordon87** [comment]
did that and it works well for me now, thanks.

closing this now.
