### ISSUE TITLE
Broken jaw when converting animations????

### ISSUE THREAD

**Issue by Jordon87** [itsmeft24/cars-research#2]
While the animation backporter works really well for me, there is one problem i currently have with it:
![332260_20220202122719_1](https://user-images.githubusercontent.com/38020644/152069009-0240af39-87cf-4001-a0fc-8839c821e062.png)

Now, this may be a problem for only me myself as i've seen the animations working fine on one of Code's YouTube community posts, but i don't know what's causing it.
In fact, i am experiencing one Python error when backporting the animations, and it's this:
![image](https://user-images.githubusercontent.com/38020644/152069458-363c1049-c5a1-4d54-bddb-3d2d6d8d180d.png)

yeah that's all i have to say, hopefully someone will be able to help me fix this problem.

**Comment by itsmeft24** [comment]
are the animations that are spitting out this error also the ones that have this jaw error? just fixed that HalfQuaternionRotationKey.as_srk bug  a couple seconds ago

**Comment by Jordon87** [comment]
welp it works now.

thanks for the fix man!
