### ISSUE TITLE
XBR extract tool doesn't work after PS2 support.

### ISSUE THREAD

**Issue by Jordon87** [itsmeft24/cars-research#3]
Compiled the latest version of the XBR extract tool, apparently the recent commits to it have broken it altogether. I can't seem to extract the files from the xbr_hashes.txt file.
![image](https://user-images.githubusercontent.com/38020644/163068755-3e6e28a3-08af-4d98-8d00-5c9b968f7932.png)

**Comment by itsmeft24** [comment]
thank you for bringing this to my attention, i believe i have identified the source of the error on line 39 of main.cpp.

**Comment by itsmeft24** [comment]
latest commit should resolve this issue. at any rate, thank you so much for catching my mistake haha
