### ISSUE TITLE
Question about the gct2tex0 converter

### ISSUE THREAD

**Issue by bingusgaming490** [itsmeft24/cars-research#5]
I've been using the gct2tex0.py to convert some textures and I have a question about transparent textures
I typed "gct2tex0.py mcq_window_bolts.gct mcq_window_bolts.tex0" and it converted to tex0 with the CL8 format and I don't think that's right

This is Lightning's window bolt texture extracted from the gct
![mcq_window_bolts](https://github.com/itsmeft24/cars-research/assets/120013221/2ae21416-ffb4-4d14-a7ba-91e63490056f)
This is the texture dumped with Dolphin Emulator
![tex1_128x64_m_bde918b4d43dabf2_fe61878c02c9138d_9](https://github.com/itsmeft24/cars-research/assets/120013221/1fbbc863-8ac2-4967-8f74-3f41dca5fac1)

Is there something I did wrong here or is this something you couldn't figure out?

**Comment by itsmeft24** [comment]
for CI8 textures, you need to dump a palette file (.plt0) alongside the tex0:
```py gct2tex0.py mcq_window_bolts.gct mcq_window_bolts.tex0 -P```
then in BrawlCrate you can give it both the tex0 and the plt0 to get the actual image
