### ISSUE TITLE
Hey Itsmeft24. I need your help

### ISSUE THREAD

**Issue by Bubi083106** [itsmeft24/cars-research#7]
I need to talk for ya.

Where can I convert CI8 to CMPR for CVG Wii/GC Textures?

I just need to resize (upscale ai no needed) for DJ's Wii textures (512x256) to (1024x512) for size like CVG/MN/RoR PS3/X360 Scales

But CvG/MN/RoR Eye Textures wants to into CMPR & 128x128 scale like HD

They're both Wii textures. But Code was doing the project for Hi-Octane

Please don't me mad at you. I'm promise behave. You need to help me for CI8 to CMPR Converter

**Comment by Bubi083106** [comment]
I just have a link
[dj_body.png](https://static.wikia.nocookie.net/modcars/images/9/97/DJ_Body.png/revision/latest?cb=20221128223237)

**Comment by itsmeft24** [comment]
I'm not willing or able to convert or create modded textures for you, however, I'll direct you to the tool [BrawlCrate](https://github.com/soopercool101/BrawlCrate/releases), which is capable of generating ``.TEX0`` files encoded in the CI8 pixel format from any generic image format.
